apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uwrp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-uwrp@sha256:59917f325844edf0efc64a81b75465938e4513512c15e3c9f2021a3b3c58f7d7
        name: my-nodejs
        resources: {}
status: {}
